import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { fixture, seedAnalysis } from './helpers.mjs';

test('real stdio process negotiates MCP, exposes tools and returns structured tool errors', async t=>{
  const f=await fixture(t); await f.output();
  const transport=new StdioClientTransport({command:process.execPath,args:[path.resolve('dist/index.js'),'--workspace',f.root,'--skills-dir',path.join(f.root,'skills'),'--config-dir',path.join(f.root,'config')],env:{PATH:process.env.PATH,SUPPORTPAGES_TELEMETRY:'0'},stderr:'pipe'});
  let stderr='';
  transport.stderr?.on('data', chunk=>stderr+=chunk);
  const client=new Client({name:'supportpages-integration-test',version:'1.0.0'});
  await client.connect(transport);
  t.after(()=>client.close());
  const {tools}=await client.listTools();
  assert.equal(tools.length,47);
  const setup = tools.find(tool => tool.name === 'supportpages_setup_hosted');
  assert.equal(setup.annotations.readOnlyHint, false);
  assert.ok(setup.inputSchema.required.includes('action'));
  assert.equal(setup.inputSchema.properties.token, undefined);
  assert.equal(tools.find(tool => tool.name === 'supportpages_status').annotations.readOnlyHint, true);
  const publish = tools.find(tool => tool.name === 'supportpages_publish_article');
  assert.equal(publish.annotations.destructiveHint, false);
  assert.equal(publish.annotations.readOnlyHint, false);
  assert.equal(publish.annotations.openWorldHint, true);
  assert.match(publish.description, /unpublished again in the web editor/);
  assert.match(publish.description, /only when the user has instructed publication/);
  assert.equal(tools.find(tool => tool.name === 'supportpages_upload_draft').annotations.destructiveHint, true);
  const status = await client.callTool({ name: 'supportpages_status', arguments: {} });
  assert.equal(status.structuredContent.result.status, 'setup_required');
  const doctor=await client.callTool({name:'supportpages_doctor',arguments:{}});
  assert.equal(doctor.structuredContent.result.credentials_configured,false);
  assert.deepEqual([doctor.structuredContent.result.telemetry.enabled,doctor.structuredContent.result.telemetry.reason],[false,'SUPPORTPAGES_TELEMETRY']);
  const validation=await client.callTool({name:'supportpages_validate_article',arguments:{artifact_dir:'output/articles/invite'}});
  assert.equal(validation.structuredContent.result.valid,true);
  const failure=await client.callTool({name:'supportpages_validate_article',arguments:{artifact_dir:'../secrets'}});
  assert.equal(failure.isError,true);
  assert.equal(failure.structuredContent.error.code,'invalid_path');
  const blocked=await client.callTool({name:'supportpages_finalize_article',arguments:{artifact_dir:'output/articles/invite',completed:true}});
  assert.equal(blocked.structuredContent.error.code,'analysis_required');
  await seedAnalysis(f.ws);
  const final=await client.callTool({name:'supportpages_finalize_article',arguments:{artifact_dir:'output/articles/invite',completed:true}});
  assert.equal(final.structuredContent.result.status,'finalized');
  assert.equal(stderr,'');
});

test('a local folder works over stdio with no credential: local status, context and saved articles', async t=>{
  const f=await fixture(t); await seedAnalysis(f.ws);
  await f.bridge.saveLocal({ version: 1, export_dir: 'output/articles', writing_style: 'minimal' });
  const transport=new StdioClientTransport({command:process.execPath,args:[path.resolve('dist/index.js'),'--workspace',f.root,'--skills-dir',path.join(f.root,'skills'),'--config-dir',path.join(f.root,'config')],env:{PATH:process.env.PATH,SUPPORTPAGES_TELEMETRY:'0'},stderr:'pipe'});
  let stderr='';
  transport.stderr?.on('data', chunk=>stderr+=chunk);
  const client=new Client({name:'supportpages-integration-test',version:'1.0.0'});
  await client.connect(transport);
  t.after(()=>client.close());
  const status=await client.callTool({name:'supportpages_status',arguments:{}});
  assert.equal(status.structuredContent.result.status,'local');
  assert.equal(status.structuredContent.result.generation_ready,true);
  const init=await client.callTool({name:'supportpages_init',arguments:{}});
  assert.equal(init.structuredContent.result.status,'local');
  const context=await client.callTool({name:'supportpages_get_context',arguments:{}});
  assert.equal(context.structuredContent.result.local,true);
  assert.match(context.structuredContent.result.writing_style,/terse quick-reference/);
  const prepared=await client.callTool({name:'supportpages_prepare_article',arguments:{title:'Invite a teammate'}});
  assert.equal(prepared.structuredContent.result.local,true);
  assert.equal(prepared.structuredContent.result.editor_url,null);
  assert.doesNotMatch(prepared.content[0].text,/publish it/);
  await f.ws.writeJson(`${prepared.structuredContent.result.artifact_dir}/article.json`,{...(await f.ws.json('output/articles/invite/article.json').catch(()=>null)) ?? {schema_version:2,title:'Invite a teammate',article_type:'how-to',blocks:[{id:'intro',type:'prose',presentation:'lead',content:'Invite someone.'}]}});
  await f.ws.writeJson(`${prepared.structuredContent.result.artifact_dir}/lint_report.json`,{all_passed:true});
  const completed=await client.callTool({name:'supportpages_complete_article',arguments:{run_id:prepared.structuredContent.result.run_id,completed:true}});
  assert.equal(completed.structuredContent.result.status,'saved');
  assert.equal(completed.structuredContent.result.markdown_path,path.join(f.root,'output/articles/invite-a-teammate/index.md'));
  assert.equal(await f.ws.exists('output/articles/invite-a-teammate/index.md'),true);
  const listed=await client.callTool({name:'supportpages_list_local_articles',arguments:{}});
  assert.equal(listed.structuredContent.result.status,'local');
  assert.equal(listed.structuredContent.result.articles.length,1);
  const upload=await client.callTool({name:'supportpages_upload_draft',arguments:{slug:'invite-a-teammate'}});
  assert.equal(upload.isError,true);
  assert.equal(upload.structuredContent.error.code,'local_workspace');
  assert.equal(upload.structuredContent.error.next_tool,'supportpages_init');
  assert.match(upload.structuredContent.error.message,/sign in or create a free SupportPages.io account.*supportpages_init with host_local=true/);
  assert.doesNotMatch(upload.structuredContent.error.message,/in (the|a) terminal|(?:wtfm|supportpages) publish\b/);
  assert.equal(stderr,'');
});
